AWSTemplateFormatVersion: '2010-09-09'
Description: Stands up a s3 bucket
Parameters:
  BucketName:
    Type: String
    Description: The name of the bucket
  Region:
    Type: String
    Description: The name of the region
Resources:
  s3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub ${BucketName}-${Region}
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        IgnorePublicAcls: true
      Tags:
        - Key: Region
          Value: !Sub ${Region}  
 